dist: xenial
os:
  - linux
  - osx

language: rust
cache: cargo
rust:
  - nightly

# only test master and tagged releases on push
# always test things that aren't pushes (like PRs)
if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        rustup component add --toolchain nightly rustfmt-preview;
        which rustfmt || cargo install --force rustfmt-nightly;
    fi

script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo fmt -v -- --check;
    fi
  - cargo build --verbose --all
  - cargo test --verbose --all
